name: Build & Deploy

on:
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build_and_deploy:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - uses: swift-actions/setup-swift@v2.1.0
              with:
                  swift-version: "5.8.1"
            - uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
            - name: Install dependencies
              run: make install
            - name: Run Build Script
              run: make run
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "build"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
